#!/usr/bin/env bats
# Tests for scripts/set-version.sh
#
# Run with: bats tests/set_version.bats
# Requires: bash, sed, awk (standard POSIX tools only)

SCRIPT="$BATS_TEST_DIRNAME/../scripts/set-version.sh"

setup() {
    TMPROOT="$(mktemp -d)"

    # Minimal Cargo.toml with a [package] version line
    cat > "$TMPROOT/Cargo.toml" <<'EOF'
[package]
name = "hvac-transcoder"
version = "5.4.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4" }
EOF

    # Minimal Cargo.lock with an hvac-transcoder entry
    cat > "$TMPROOT/Cargo.lock" <<'EOF'
# This file is automatically @generated by Cargo.
[[package]]
name = "anyhow"
version = "1.0.0"

[[package]]
name = "hvac-transcoder"
version = "5.4.0"
dependencies = ["anyhow"]
EOF

    mkdir -p "$TMPROOT/packaging/aur" "$TMPROOT/packaging/homebrew"

    cat > "$TMPROOT/packaging/aur/PKGBUILD" <<'EOF'
pkgname=hvac
pkgver=5.4.0
pkgrel=1
EOF

    cat > "$TMPROOT/packaging/homebrew/hvac.rb" <<'EOF'
class Hvac < Formula
  url "https://github.com/JackDanger/hvac/archive/v5.4.0.tar.gz"
end
EOF

    # Point the script at our tmp tree by creating a VERSION file there and
    # calling the script with ROOT overridden via a wrapper.
    printf '5.5.0\n' > "$TMPROOT/VERSION"

    # Wrapper: override ROOT so the script edits TMPROOT, not the real repo.
    WRAPPER="$TMPROOT/run.sh"
    cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
set -euo pipefail
export BATS_TEST_DIRNAME="$BATS_TEST_DIRNAME"
# Source the real script but override ROOT
ROOT="$TMPROOT"
$(sed '1{/^#!/d}; /^SCRIPT_DIR=/d; /^ROOT=/d' "$SCRIPT")
EOF
    chmod +x "$WRAPPER"
    WRAPPER_SCRIPT="$WRAPPER"
}

teardown() {
    rm -rf "$TMPROOT"
}

@test "propagates version to Cargo.toml" {
    bash "$WRAPPER_SCRIPT"
    grep -q 'version = "5.5.0"' "$TMPROOT/Cargo.toml"
}

@test "propagates version to Cargo.lock" {
    bash "$WRAPPER_SCRIPT"
    grep -q '"5.5.0"' "$TMPROOT/Cargo.lock"
}

@test "does not touch anyhow version in Cargo.lock" {
    bash "$WRAPPER_SCRIPT"
    grep -q '"1.0.0"' "$TMPROOT/Cargo.lock"
}

@test "propagates version to PKGBUILD" {
    bash "$WRAPPER_SCRIPT"
    grep -q '^pkgver=5.5.0' "$TMPROOT/packaging/aur/PKGBUILD"
}

@test "propagates version to homebrew formula" {
    bash "$WRAPPER_SCRIPT"
    grep -q 'archive/v5.5.0.tar.gz' "$TMPROOT/packaging/homebrew/hvac.rb"
}

@test "rejects malformed version with internal spaces" {
    printf '5.5. 0\n' > "$TMPROOT/VERSION"
    run bash "$WRAPPER_SCRIPT"
    [ "$status" -ne 0 ]
    [[ "$output" == *"VERSION must be X.Y.Z"* ]]
}

@test "rejects version missing patch segment" {
    printf '5.5\n' > "$TMPROOT/VERSION"
    run bash "$WRAPPER_SCRIPT"
    [ "$status" -ne 0 ]
}

@test "does not mutate [package] version for dependency-style version lines" {
    # A dep like `clap = { version = "4" }` should never be modified;
    # only the bare `^version = "..."` [package] line must change.
    bash "$WRAPPER_SCRIPT"
    grep -q 'clap = { version = "4" }' "$TMPROOT/Cargo.toml"
}
