#!/usr/bin/env bash
# Read VERSION from the repo root and propagate it to every place that
# needs a hardcoded version string: Cargo.toml, the AUR PKGBUILD, and the
# in-tree Homebrew source formula.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

VERSION="$(tr -d '[:space:]' < "$ROOT/VERSION")"

if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "error: VERSION must be X.Y.Z, got: '$VERSION'" >&2
  exit 1
fi

echo "Setting version to $VERSION"

# Cargo.toml — first version = "..." line in [package]
sed -i.bak 's/^version = "[^"]*"/version = "'"$VERSION"'"/' "$ROOT/Cargo.toml"
rm -f "$ROOT/Cargo.toml.bak"

# AUR PKGBUILD
sed -i.bak "s/^pkgver=.*/pkgver=$VERSION/" "$ROOT/packaging/aur/PKGBUILD"
rm -f "$ROOT/packaging/aur/PKGBUILD.bak"

# In-tree Homebrew source formula (the one used for reference; the tap
# formula is regenerated by release.yml from the published binaries)
sed -i.bak "s|archive/v[0-9]*\.[0-9]*\.[0-9]*\.tar\.gz|archive/v$VERSION.tar.gz|" \
  "$ROOT/packaging/homebrew/hvac.rb"
rm -f "$ROOT/packaging/homebrew/hvac.rb.bak"

echo "Done. Files updated:"
echo "  Cargo.toml"
echo "  packaging/aur/PKGBUILD"
echo "  packaging/homebrew/hvac.rb"
echo ""
echo "Next: update CHANGELOG.md, commit, tag v$VERSION, and push."
