# This is the source-build formula kept in-tree for reference.
# The released formula at JackDanger/homebrew-tap is generated by
# .github/workflows/release.yml from the published binary tarballs.
class Hvac < Formula
  desc "GPU-accelerated media transcoder (HEVC/h265 via NVENC, VAAPI, VideoToolbox)"
  homepage "https://github.com/JackDanger/hvac"
  url "https://github.com/JackDanger/hvac/archive/v5.2.0.tar.gz"
  sha256 "PLACEHOLDER" # Update with actual sha256 on release
  license "MIT"

  depends_on "rust" => :build
  depends_on "ffmpeg"

  def install
    system "cargo", "install", *std_cargo_args
    etc.install "config.yaml" => "hvac/config.yaml"
  end

  def caveats
    <<~EOS
      hvac requires a GPU with hardware HEVC encoding support:
        - macOS: Apple VideoToolbox (built-in on Apple Silicon and recent Intel Macs)
        - Linux: NVIDIA NVENC or Intel VAAPI

      A default config has been installed to:
        #{etc}/hvac/config.yaml
    EOS
  end

  test do
    assert_match "hvac", shell_output("#{bin}/hvac --help")
  end
end
